name: humio
description: Analytics and error logging from your Flutter app to Humio - simple and easy.
version: 0.1.3
homepage: https://holion.dk
repository: https://github.com/holion/flutter-humio

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
