trigger:
  - master
  - feature/test

variables:
  flutterChannel: stable
  flutterVersion: latest

jobs:
  - job: BuildAndPublish
    displayName: Build and publish package
    steps:
      - task: hey24sheep.flutter.flutter-install.FlutterInstall@0
        displayName: Installing flutter
        inputs:
          channel: $(flutterChannel)
          version: $(flutterVersion)

      - script: $(FlutterToolPath)/flutter doctor -v
        displayName: Flutter Doctor

      - task: DownloadSecureFile@1
        displayName: Downloading secure file containing Humio ingest token
        name: humioIngestToken
        inputs:
          secureFile: .humio-ingest-token

      - script: cat $(humioIngestToken.secureFilePath) > .humio-ingest-token
        displayName: Writing secure file to file expected by tests
          
      - script: $(FlutterToolPath)/flutter test
        displayName: Running tests

      - script: $(FlutterToolPath)/flutter pub publish -f
        displayName: Publishing package
        workingDirectory: .
