trigger:
  - master
  - feature/test

variables:
  flutterChannel: stable
  flutterVersion: latest

# pool:
#   name: default

jobs:
  - job: BuildAndPublish
    displayName: Build and publish package
    steps:

      - task: DownloadSecureFile@1
        name: .humio-ingest-token
        inputs:
          secureFile: .humio-ingest-token
          
      - task: hey24sheep.flutter.flutter-install.FlutterInstall@0
        displayName: Installing flutter
        inputs:
          channel: $(flutterChannel)
          version: $(flutterVersion)

      - script: $(FlutterToolPath)/flutter doctor -v
        displayName: Flutter Doctor

      - task: DownloadSecureFile@1
        name: .humio-ingest-token
        inputs:
          secureFile: .humio-ingest-token

      - script: $(FlutterToolPath)/flutter test
        displayName: Running tests

      # - script: $(FlutterToolPath)/flutter pub publish -f
      #   displayName: Publishing package
      #   workingDirectory: .
